export const organizerApiFallback = {
  eventTypesList: 'Unable to load event types.',
  eventTypeCreate: 'Unable to create event type.',
  eventTypeUpdate: 'Unable to update event type.',
  notificationRulesGet: 'Unable to load notification rules.',
  notificationRulesPut: 'Unable to save notification rules.',
  notificationsRun: 'Unable to run notification workflows.',
  availabilityGet: 'Unable to load availability.',
  availabilityRulesPut: 'Unable to update availability rules.',
  availabilityOverridesPut: 'Unable to update availability overrides.',
  timeOffList: 'Unable to load time-off blocks.',
  timeOffCreate: 'Unable to create time-off block.',
  timeOffDelete: 'Unable to delete time-off block.',
  timeOffHolidayImport: 'Unable to import holiday blocks.',
  teamsList: 'Unable to load teams.',
  teamCreate: 'Unable to create team.',
  teamMembersList: 'Unable to load team members.',
  teamMemberCreate: 'Unable to add team member.',
  teamEventTypesList: 'Unable to load team event types.',
  teamEventTypeCreate: 'Unable to create team event type.',
  webhooksList: 'Unable to load webhooks.',
  webhookCreate: 'Unable to create webhook.',
  webhookPatch: 'Unable to update webhook.',
  webhookRun: 'Unable to run webhook deliveries.',
  calendarStatus: 'Unable to load calendar status.',
  calendarGoogleConnectStart: 'Unable to start Google calendar connection.',
  calendarGoogleConnectComplete: 'Unable to complete Google calendar connection.',
  calendarMicrosoftConnectStart: 'Unable to start Microsoft calendar connection.',
  calendarMicrosoftConnectComplete: 'Unable to complete Microsoft calendar connection.',
  calendarConnectionDisconnect: 'Unable to disconnect calendar.',
  calendarConnectionSync: 'Unable to sync calendar.',
  calendarConnectionPreferences: 'Unable to update calendar preferences.',
  profileGet: 'Unable to load profile.',
  profileUpdate: 'Unable to update profile.',
  onboardingComplete: 'Unable to complete onboarding.',
  writebackStatus: 'Unable to load writeback status.',
  writebackRun: 'Unable to run writeback queue.',
} as const;
